version: "3"
services:
  lerna:
    build:
      context: .
    environment:
      - NPM_TOKEN=
    working_dir: /app
    volumes:
      - ./:/app
      - ${HOME}/.gitignore:/root/.gitignore
      - ${HOME}/.gitconfig:/etc/gitconfig
      - ${HOME}/.ssh:/root/.ssh