export enum TransferStatusDefaultBankAccount {
  REQUESTED = 'REQUESTED',
  NEEDS_CHECK = 'NEEDS_CHECK',
  CHECK_FAILED = 'CHECK_FAILED',
  EXECUTED = 'EXECUTED',
  AWAITING_EXECUTION = 'AWAITING_EXECUTION',
  REJECTED = 'REJECTED',
  INVALID_BANK_ACCOUNT = 'INVALID_BANK_ACCOUNT',
  CANCELED = 'CANCELED',
}
