export enum DocumentsTypesLegalPerson {
  EI_DOC = 'EI_DOC',
  MEI_DOC = 'MEI_DOC',
  LTDA_DOC = 'LTDA_DOC',
  CONSTITUTION_RECORD = 'CONSTITUTION_RECORD',
  EIRELI_DOC = 'EIRELI_DOC',
  CONTRACT_AGREEMENT = 'CONTRACT_AGREEMENT',
  COMPANY_FORMATION_MEETING_MINUTES = 'COMPANY_FORMATION_MEETING_MINUTES',
}
