name: Juno SDK CI/CD

concurrency:
  group: ci-cd-juno-node-sdk-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get DeployCounter
        uses: actions/checkout@v2
        with:
          repository: anthorteam/deploy-counter
          ref: main
          path: ./.github/deploy-counter
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.WORK_DIR }}/yarn.lock
      
      - name: Install dependencies
        run: |
          yarn install
      
      - name: Build
        run: |
          yarn build

      - name: Count deploy
        id: count-deploy
        uses: ./.github/deploy-counter/action
        continue-on-error: true
        with:
          DEPLOYMENT_NAME: juno-node-sdk
          DEPLOY_COUNTER_URL: https://${{ secrets.DEPLOY_COUNTER_URL }}/v1/deploy/
          DEPLOY_COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
          DEPLOY_ENVIRONMENT: "2"

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Notify deploy issue
        if: ${{ failure() }}
        uses: ./.github/deploy-counter/notify-issue
        continue-on-error: true
        with:
          DEPLOYMENT_NAME: juno-node-sdk
          DEPLOY_COUNTER_URL: https://${{ secrets.DEPLOY_COUNTER_URL }}/v1/deploy/
          DEPLOY_COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
          DEPLOY_ID: ${{ steps.count-deploy.outputs.DEPLOY_ID }}