name: Juno SDK CI/CD

concurrency:
  group: ci-cd-juno-node-sdk-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      
      - name: Install dependencies
        run: |
          yarn install
      
      - name: Build
        run: |
          yarn lerna bootstrap

     - name: Deploy
        run: lerna version --force-git-tag -y --conventional-commits --conventional-graduate          
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
