name: Juno SDK CI/CD

concurrency:
  group: ci-cd-juno-node-sdk-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn lerna bootstrap

      - name: Deploy
        continue-on-error: true
        id: graduateRelease
        run: yarn lerna version --conventional-graduate --conventional-commits --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump Prod Version Fallback
        if: ${{ always() && steps.graduateRelease.outcome == 'failure'  }}
        run: |
          echo Falling back to non-graduate release due to https://github.com/lerna/lerna/issues/2532
          git stash
          yarn lerna version --conventional-commits --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}